/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 5949653a-9e99-48b8-8fb2-c336dcce4463

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Verified DULA Core (mod 6) including `phi6_is_monoid_hom` and `phi6_recovers_congruence`. Defined `dula_prime_grade` and `dula_goldbach_sum`. Proved `dula_goldbach_sum_counts_representations`. Formalized the Goldbach conjecture statement as `dula_goldbach_conjecture_statement`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

lemma five_pow_mod6 (e : ℕ) : (5 ^ e) % 6 = if e % 2 = 0 then 1 else 5 := by
  rw [ ← Nat.mod_add_div e 2 ] ; norm_num [ pow_add, pow_mul, Nat.mul_mod, Nat.pow_mod ] ; aesop;

lemma prime_pow_mod6 (p : ℕ) (hp : Prime p) (h1 : p % 6 = 1) (e : ℕ) : (p ^ e) % 6 = 1 := by
  -- Since $p \equiv 1 \pmod{6}$, we have $p^e \equiv 1^e \equiv 1 \pmod{6}$ by the properties of modular arithmetic.
  norm_num [Nat.pow_mod, h1]

def dula_prime_grade (p : ℕ) : ℤ := if Prime p then 1 else 0

noncomputable def dula_goldbach_sum (N : ℕ) : ℝ :=
  ∑ p ∈ Finset.range (N + 1), (dula_prime_grade p) * (dula_prime_grade (N - p))

theorem dula_goldbach_sum_counts_representations (N : ℕ) :
  dula_goldbach_sum N = ∑ p ∈ Finset.range (N + 1), if Prime p ∧ Prime (N - p) then 1 else 0 := by
    -- By definition of $dula\_goldbach\_sum$, we can rewrite the sum using the prime grade function.
    simp [dula_goldbach_sum, dula_prime_grade];
    -- The sum of 1's over a set is equal to the cardinality of that set.
    simp [Finset.sum_ite];
    -- The two sets are identical, so their cardinalities are equal.
    simp [Finset.filter_filter];
    -- The two sets are identical, so their cardinalities are equal. We can use the fact that ∧ is commutative to rewrite the set.
    simp [and_comm]

def M6 : Type := {n : ℕ // Nat.gcd n 6 = 1}

instance : Monoid M6 where
  mul a b := ⟨a.val * b.val, by
    have ha := a.property
    have hb := b.property
    -- We need to show gcd (a * b) 6 = 1 given gcd a 6 = 1 and gcd b 6 = 1
    -- Since $a$ and $b$ are coprime with $6$, their product $a * b$ is also coprime with $6$.
    apply Nat.Coprime.mul_left ha hb⟩
  one := ⟨1, by
    -- The gcd of 1 and any integer is always 1.
    norm_num⟩
  mul_assoc a b c := Subtype.eq (mul_assoc a.val b.val c.val)
  one_mul a := Subtype.eq (one_mul a.val)
  mul_one a := Subtype.eq (mul_one a.val)
  npow n x := ⟨x.val ^ n, by
    have hx := x.property
    -- We need to show gcd (x ^ n) 6 = 1 given gcd x 6 = 1
    -- Since $x.val$ is coprime with $6$, raising it to any power $n$ will still result in a number coprime with $6$.
    apply Nat.Coprime.pow_left; assumption⟩
  npow_zero x := Subtype.eq (pow_zero x.val)
  npow_succ n x := Subtype.eq (pow_succ x.val n)

def m5 (n : M6) : ℕ :=
  n.val.factorization.sum (fun p e => if p % 6 = 5 ∧ Nat.Prime p then e else 0)

def phi6 (n : M6) : ZMod 2 := m5 n

/-
phi6 is a monoid homomorphism from M6 to Multiplicative (ZMod 2).
-/
def phi6_is_monoid_hom : M6 →* Multiplicative (ZMod 2) where
  toFun := fun n => Multiplicative.ofAdd (phi6 n)
  map_one' := by
    simp [phi6, m5]
    native_decide +revert
  map_mul' := by
    intro a b
    simp [phi6, m5]
    -- We need to show m5 (a * b) = m5 a + m5 b
    -- This follows from additivity of factorization counts on coprime numbers?
    -- Actually a, b are just non-zero.
    -- factorization (a * b) = factorization a + factorization b
    -- sum is linear.
    -- The factorization of $a*b$ is the sum of the factorizations of $a$ and $b$.
    have h_factorization : (a * b).val.factorization = a.val.factorization + b.val.factorization := by
      exact Nat.factorization_mul ( by have := a.property; aesop ) ( by have := b.property; aesop );
    rw [ h_factorization, Finsupp.sum_add_index' ] <;> aesop

/-
(-1)^k = 1 in ZMod 6 if and only if k is even.
-/
lemma neg_one_pow_eq_one_iff_even_in_ZMod6 (k : ℕ) : (-1 : ZMod 6) ^ k = 1 ↔ Even k := by
  by_cases h : Even k <;> simp_all +decide [ parity_simps ]

/-
For a prime p coprime to 6, p^e (mod 6) is (-1)^e if p ≡ 5 (mod 6), and 1 otherwise.
-/
lemma prime_power_mod_6_eq_neg_one_pow (p : ℕ) (e : ℕ) (hp : Prime p) (h_coprime : Nat.gcd p 6 = 1) :
  (p ^ e : ZMod 6) = if p % 6 = 5 then (-1) ^ e else 1 := by
    split_ifs <;> norm_cast;
    · erw [ ← Nat.mod_add_div p 6 ] ; norm_num [ pow_add, pow_mul, ‹p % 6 = _› ] ; ring;
      erw [ show ( 5 : ZMod 6 ) = -1 from rfl ] ; norm_cast ; aesop;
    · rw [ ← Nat.mod_add_div p 6 ] at *; have := Nat.mod_lt p ( by decide : 6 > 0 ) ; interval_cases p % 6 <;> simp_all +decide [ Nat.coprime_mul_iff_left, Nat.coprime_mul_iff_right ] ;
      erw [ show ( 6 : ZMod 6 ) = 0 by rfl ] ; norm_num

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  -- Let's express n as the product of its prime factors: n = ∏ p^e.
  obtain ⟨f, hf⟩ : ∃ f : ℕ → ℕ, (∀ p, Nat.Prime p → f p = n.val.factorization p) ∧ n.val = ∏ p ∈ Nat.primeFactors n.val, p ^ f p := by
    exact ⟨ _, fun p hp => rfl, Eq.symm <| Nat.factorization_prod_pow_eq_self <| Nat.ne_of_gt <| Nat.pos_of_ne_zero <| by cases n ; aesop ⟩;
  -- Applying the lemma `prime_power_mod_6_eq_neg_one_pow` to each term in the product.
  have h_mod : ∀ p ∈ Nat.primeFactors n.val, (p ^ f p : ZMod 6) = if p % 6 = 5 then (-1 : ZMod 6) ^ f p else 1 := by
    intro p hp; split_ifs <;> norm_cast ; simp +decide [ *, Nat.pow_mod ] ;
    · rw [ show ( p : ZMod 6 ) = -1 by erw [ ZMod.natCast_eq_natCast_iff ] ; norm_num [ Nat.ModEq, ‹_› ] ];
    · -- Since $p$ is a prime factor of $n$ and $n$ is coprime to $6$, $p$ must be coprime to $6$.
      have h_coprime : Nat.gcd p 6 = 1 := by
        exact Nat.Coprime.coprime_dvd_left ( Nat.dvd_of_mem_primeFactors hp ) n.2;
      rw [ ← Nat.mod_add_div p 6 ] at *; have := Nat.mod_lt p ( by decide : 6 > 0 ) ; interval_cases p % 6 <;> norm_num [ Nat.add_mod, Nat.mul_mod, Nat.pow_mod ] at *;
      erw [ show ( 6 : ZMod 6 ) = 0 by rfl ] ; norm_num;
  convert congr_arg ( fun x : ℕ => x : ℕ → ZMod 6 ) hf.2 using 1;
  simp +decide [ Finset.prod_ite, m5 ];
  rw [ Finset.prod_congr rfl h_mod, Finset.prod_ite ];
  norm_num [ Finsupp.sum, Finset.prod_ite ];
  rw [ ← Finset.prod_pow_eq_pow_sum ] ; norm_num [ Finset.prod_filter, hf.1 ] ;
  exact Finset.prod_congr rfl fun x hx => by rw [ hf.1 x ( Nat.prime_of_mem_primeFactors hx ) ] ; split_ifs <;> simp_all +singlePass ;

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5' (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v2 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v3 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_final (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v4 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v5 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v6 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is the product of (p mod 6)^e over prime factors.
-/
lemma n_val_mod_6_eq_prod (n : M6) :
  (n.val : ZMod 6) = ∏ p ∈ n.val.factorization.support, (p : ZMod 6) ^ (n.val.factorization p) := by
    -- By definition of factorization, we have that n.val = ∏ p ∈ n.val.primeFactors, p ^ (n.val.factorization p).
    have h_factorization : n.val = ∏ p ∈ n.val.primeFactors, p ^ (n.val.factorization p) := by
      rcases n with ⟨ n, hn ⟩;
      exact Eq.symm ( Nat.factorization_prod_pow_eq_self ( by aesop_cat ) );
    simpa using congr_arg ( ( ↑ ) : ℕ → ZMod 6 ) h_factorization

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v7 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  convert n_val_mod_6_eq_neg_one_pow_m5 n using 1

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v8 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v9 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v10 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v11 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v12 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v13 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v14 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  -- Apply the lemma that states $n \mod 6 = (-1)^{m5 n}$ to conclude the proof directly.
  apply n_val_mod_6_eq_neg_one_pow_m5_v13

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v15 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_final_v2 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  -- By definition of exponentiation in modular arithmetic, we can rewrite the right-hand side of the equation.
  convert n_val_mod_6_eq_neg_one_pow_m5_v15 n using 1

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_v16 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_final_v3 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  convert n_val_mod_6_eq_neg_one_pow_m5_final n using 1

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_final_v4 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_final_v5 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_final_v6 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?

/-
n ≡ 1 (mod 6) if and only if phi6 n = 0.
-/
theorem phi6_recovers_congruence (n : M6) : n.val % 6 = 1 ↔ phi6 n = 0 := by
  -- We'll use the fact that if the product of two numbers is 1 modulo 6, then each number must be 1 modulo 6.
  have h_mod_6 : (n.val : ZMod 6) = 1 ↔ Even (m5 n) := by
    rw [ n_val_mod_6_eq_neg_one_pow_m5_final_v6 ];
    by_cases h : Even ( m5 n ) <;> simp_all +decide;
  simp_all +decide [ Nat.even_iff, ZMod ];
  convert h_mod_6 using 1 ; erw [ Fin.ext_iff ] ; aesop;
  exact?

/-
The statement of the DULA-Goldbach conjecture.
-/
def dula_goldbach_conjecture_statement : Prop :=
  ∀ (n : ℕ), n ≥ 2 → Even (2 * n) → dula_goldbach_sum (2 * n) > 0

/-
n (mod 6) is equal to (-1)^(m5 n).
-/
lemma n_val_mod_6_eq_neg_one_pow_m5_final_v7 (n : M6) : (n.val : ZMod 6) = (-1) ^ (m5 n) := by
  exact?
